name: Valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update
      run: sudo apt-get update
    - name: Install-Valgrind
      run: sudo apt-get install valgrind

