# Name of the project
PROJECT_NAME = HOTEL_MANAGEMENT_SYSTEM

#Doxyfile folder
DOC = documentation

#All source code files
SRC = hotel.c\
src/hotel_operations.c

#All test source files
TEST_SRC = src/hotel_operations.c\
test/test_hotel_operations.c\
unity/unity.c

TEST_OUTPUT = Test_fun.out

#All include folders with header files
INC = -Iinc\
-Iunity\

#Project Output Name
PROJECT_OUTPUT = hotel.out

#Document files
DOCUMENTATION_OUTPUT = documentation/html

Build:
     gcc function.c test_hotel.c unity/unity.c -Iunity
Run:
